-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS Usuario
(
    "Nombre" character varying(100),
    "Apellido" character varying(100),
    "Correo" character varying(250) NOT NULL,
    "Ciudad" character varying(150),
    "Id_Comuna" integer NOT NULL,
    "Fecha_Nacimiento" date,
    "Imagen_Perfil" character varying(200),
    "Id_Perfil" integer NOT NULL,
    "Password" character varying(100) NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "Correo" PRIMARY KEY ("Correo")
);

CREATE TABLE IF NOT EXISTS Comuna
(
    "Id_Comuna" serial NOT NULL,
    "Nombre_Comuna" character varying(150),
    CONSTRAINT "Id_Comuna" PRIMARY KEY ("Id_Comuna")
);

CREATE TABLE IF NOT EXISTS Perfiles
(
    "Id_Perfil" serial NOT NULL,
    "Nombre_Perfil" character varying(15),
    CONSTRAINT "Id_Perfil" PRIMARY KEY ("Id_Perfil")
);

CREATE TABLE IF NOT EXISTS Contacto
(
    "Id_Contacto" bigserial NOT NULL,
    "Nombre" character varying(100),
    "Apellido" character varying(100),
    "Correo" character varying(250),
    "Empresa" character varying(100),
    "Telefono" character varying(50),
    "Mensaje" character varying(450),
    PRIMARY KEY ("Id_Contacto")
);

CREATE TABLE IF NOT EXISTS Producto
(
    "Id_Producto" bigserial NOT NULL,
    "Nombre_Producto" character varying(30),
    "Id_Categoria" integer NOT NULL,
    "Precio" integer,
    "Ciudad" character varying(50),
    "Id_Comuna" integer NOT NULL,
    "Id_Local" integer NOT NULL,
    "Imagen" character varying(200),
    "Descripcion" character varying(500),
    CONSTRAINT "Id_Producto" PRIMARY KEY ("Id_Producto")
);

CREATE TABLE IF NOT EXISTS Local
(
    "Id_Local" serial NOT NULL,
    "Nombre_Local" character varying(100),
    "Id_Comuna" integer NOT NULL,
    CONSTRAINT "Id_Local" PRIMARY KEY ("Id_Local")
);

CREATE TABLE IF NOT EXISTS Comentarios
(
    "Id_Comentarios" bigserial NOT NULL,
    "Correo" character varying(250),
    "Comentario" character varying(500),
    "Id_Producto" bigint,
    CONSTRAINT "Id_Comentarios" PRIMARY KEY ("Id_Comentarios")
);

CREATE TABLE IF NOT EXISTS Categoria
(
    "Id_Categoria" serial NOT NULL,
    "Categoria" character varying(50),
    CONSTRAINT "Id_Categoria" PRIMARY KEY ("Id_Categoria")
);

CREATE TABLE IF NOT EXISTS Favoritos
(
    "Id_Favoritos" bigserial NOT NULL,
    "Correo" character varying(250) NOT NULL,
    "Id_Producto" bigint NOT NULL,
    CONSTRAINT "Id_Favoritos" PRIMARY KEY ("Id_Favoritos")
);

ALTER TABLE IF EXISTS Usuario
    ADD CONSTRAINT "Id_Comuna" FOREIGN KEY ("Id_Comuna")
    REFERENCES Comuna ("Id_Comuna") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS Usuario
    ADD CONSTRAINT "Id_Perfil" FOREIGN KEY ("Id_Perfil")
    REFERENCES Perfiles ("Id_Perfil") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS Producto
    ADD CONSTRAINT "Id_Comuna" FOREIGN KEY ("Id_Comuna")
    REFERENCES Comuna ("Id_Comuna") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS Producto
    ADD CONSTRAINT "Id_Local" FOREIGN KEY ("Id_Local")
    REFERENCES Local ("Id_Local") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS Producto
    ADD CONSTRAINT "Id_Categoria" FOREIGN KEY ("Id_Categoria")
    REFERENCES Categoria ("Id_Categoria") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS Local
    ADD CONSTRAINT "Id_Comuna" FOREIGN KEY ("Id_Comuna")
    REFERENCES Comuna ("Id_Comuna") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS Comentarios
    ADD CONSTRAINT "Id_Producto" FOREIGN KEY ("Id_Producto")
    REFERENCES Producto ("Id_Producto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS Favoritos
    ADD CONSTRAINT "Id_Producto" FOREIGN KEY ("Id_Producto")
    REFERENCES Producto ("Id_Producto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;